name = "kafka-connector"
title = "MongoDB Kafka Connector"
intersphinx = ["https://www.mongodb.com/docs/manual/objects.inv"]
toc_landing_pages = ["/introduction", "/tutorials", "/sink-connector", "/source-connector", "/sink-connector/configuration-properties", "/source-connector/configuration-properties", "/sink-connector/fundamentals", "/source-connector/fundamentals", "/source-connector/usage-examples", "/security-and-authentication", "/troubleshooting"]

[constants]
connector = "MongoDB Kafka Connector"
connector-long = "MongoDB Connector for Apache Kafka"
kafka = "Apache Kafka"
kafka-connect = "Kafka Connect"
kafka-connect-long = "Confluent Kafka Connect"
avro-long = "Apache Avro"
avro = "Avro"
connector_version="1.5"
connector_driver_version="4.2"
connector_patch_version="1"
connector_driver_url_base="https://mongodb.github.io/mongo-java-driver/{+connector_driver_version+}/"
connector_version_github_tag="r{+connector_version+}.{+connector_patch_version+}"
connector_kafka_version_major="2"
connector_kafka_version_minor="6"
connector_kafka_version_docs="https://kafka.apache.org/{+connector_kafka_version_major+}{+connector_kafka_version_minor+}"
sink-connector="MongoDB Kafka sink connector"
source-connector="MongoDB Kafka source connector"
sink-connector-title="MongoDB Kafka Sink Connector"
source-connector-title="MongoDB Kafka Source Connector"
connector_driver_api_doc_url_base="https://mongodb.github.io/mongo-java-driver/{+connector_driver_version+}/"
pipeline-size = "2.4 GB"
default-heartbeat-topic = "__mongodb_heartbeats"
mongodb-port-mapping="35001"
jmx-port-mapping="35000"
sandbox-directory="kafka-edu/docs-examples/mongodb-kafka-base/"
win-sandbox-directory="kafka-edu\\docs-examples\\mongodb-kafka-base\\"
